export enum Constants {
    GET_SETTINGS = 'GET_SETTINGS',
    SET_SETTINGS = 'SET_SETTINGS',
    DISPLAY_ENABLE ='DISPLAY_ENABLE',
    DISPLAY_DISABLE ='DISPLAY_DISABLE',
    GPS_ENABLE ='GPS_ENABLE',
    GPS_DISABLE ='GPS_DISABLE',
    NTP_ENABLE ='NTP_ENABLE',
    NTP_DISABLE ='NTP_DISABLE',
    NTP_CYCLE ='NTP_CYCLE',
    NTP_ADD_ADRESS_ITEM ='NTP_ADD_ADRESS_ITEM',
    NTP_REMOVE_ADRESS_ITEM ='NTP_REMOVE_ADRESS_ITEM',
    RTC_ENABLE ='RTC_ENABLE',
    RTC_DISABLE ='RTC_DISABLE',
    RTC_CYCLE ='RTC_CYCLE',

 

}